# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# CSS 143B
# This file is for GitHub grading

# DO NOT CHANGE

name: css 143 grader

on:
  # Uncomment the following two line to run test when you push to main in your own branch (not for homework)
  #push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]

jobs:
  CSS143B_Grader_Bot:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
#      - name: Verify PR base repo
#        run: bash .github/workflows/check_PR_target_repo.sh
#      - name: Verify no changes to the main branch
#        run: bash .github/workflows/check_no_change_to_main.sh
#      - name: Verify no changes to the grader scripts
#        run: bash .github/workflows/check_no_change_to_grader.sh
      - name: Build and run unit tests
#        run: mvn -B -ntp verify --file pom.xml
        run: mvn -B -ntp verify --file pom.xml -P existence-tests
        continue-on-error: true
      # - name: Verify submission not past due date
      #   run: bash .github/workflows/check_due_date.sh
      - name: Run PMD
        run: mvn pmd:pmd
      - name: Print effective POM
        run: mvn help:effective-pom
      - name: List PMD report directory
        run: ls -la target
      - name: Parse Test Results and Generate Report
        run: python .github/workflows/generate_report.py
        env:
          PYTHONIOENCODING: utf-8
      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: ./report.txt
      # - name: Cheer!
      #   run: bash .github/workflows/success.sh
